wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: Organization
epochs:
  desc: null
  value: 200
weightname:
  desc: null
  value: res_6
num_step_per_epoch:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1705485341.179787
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.11
      5: 0.16.2
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
